dynamixels:
    dxl_1:
        # assembly offset position (rad)
        offset_position: -3.1415
        # home position (rad)
        default_home_position: 0.0
        direction: 1
        # assembly direction (1 or -1)
        limit_position_max: 2.089
        limit_position_min: -2.093
        position_P_gain: 1292
        position_I_gain: 163
        position_D_gain: 0
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 100  # profile acc and vel used by dxl motors
        velocity_profile: 200

    dxl_2:
        offset_position: 3.1415
        default_home_position: 0.0
        direction: -1
        limit_position_max: 1.919
        limit_position_min: -1.919
        position_P_gain: 1292
        position_I_gain: 13
        position_D_gain: 0
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 75  # profile acc and vel used by dxl motors
        velocity_profile: 150

    dxl_3:
        offset_position: -3.1415
        default_home_position: 0.0
        direction: 1
        limit_position_max: 2.53
        limit_position_min: -2.529
        position_P_gain: 1536
        position_I_gain: 0
        position_D_gain: 480
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 50  # profile acc and vel used by dxl motors
        velocity_profile: 100
