SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)

SET(RASPBERRY_ROOT_PATH $ENV{HOME}/raspberrypi/rootfs)

SET(CMAKE_C_COMPILER $ENV{HOME}/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_CXX_COMPILER $ENV{HOME}/raspberrypi/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-g++)

SET(CMAKE_FIND_ROOT_PATH "${RASPBERRY_ROOT_PATH};${RASPBERRY_ROOT_PATH}/lib/aarch64-linux-gnu/")
#SET(CMAKE_PREFIX_PATH /opt/ros/melodic ${RASPBERRY_ROOT_PATH}/usr)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

SET(LD_LIBRARY_PATH ${RASPBERRY_ROOT_PATH}/lib)
