alert_report:
  get_rom_usage:
    frequency: 'LOW'
    threshold: 90
#  get_cpu_usage:
#    frequency: 'HIGH'
#    threshold: 90
  get_cpu_temperature:
    frequency: 'HIGH'
    threshold: 70
  get_ram_usage:
    frequency: 'HIGH'
    threshold: 90

auto_diagnosis: 'auto_diagnosis.py'