#!/usr/bin/env python

import signal
import sys

import rospy

from python_qt_binding.QtWidgets import QApplication

import niryo_end_effector_publisher_gui

if __name__ == '__main__':
    try:
        rospy.init_node('niryo_end_effector_publisher_gui')
        app = QApplication(sys.argv)
        app.setApplicationDisplayName("End Effector Publisher")
        jsp_gui = niryo_end_effector_publisher_gui.EndEffectorPublisherGui()
        jsp_gui.show()

        signal.signal(signal.SIGINT, signal.SIG_DFL)
        sys.exit(app.exec_())

    except rospy.ROSInterruptException:
        pass
