#
#
# Validation for a ArmMoveCommand
# (taken from urdf)
#

position_limits:
    x:
        min: -0.50
        max: 0.50
    y:
        min: -0.50
        max: 0.50
    z:
        min: -0.15
        max: 0.60

rpy_limits:
    roll:
        min: -3.142
        max: 3.142
    pitch:
        min: -3.142
        max: 3.142
    yaw:
        min: -3.142
        max: 3.142

