# Settings for ros_control control loop
hardware_control_loop:
    loop_hz: 25

# Publish all joint states -----------------------
joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 50

controller_list:
    - name: "niryo_robot_follow_joint_trajectory_controller"
      action_ns: follow_joint_trajectory
      type: FollowJointTrajectory
      default: true
      joints:
          - joint_1
          - joint_2
          - joint_3
          - joint_4
          - joint_5
          - joint_6

# Joint Trajectory Controller - position based -----------------------
niryo_robot_follow_joint_trajectory_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
        - joint_1
        - joint_2
        - joint_3
        - joint_4
        - joint_5
        - joint_6
    constraints:
        goal_time: 1.0
        stopped_velocity_tolerance: 0.001
        # Trajectory threshold are high to disable it since we do not correct trajectory
        joint_1: {trajectory: 6.28, goal: 0.001}
        joint_2: {trajectory: 6.28, goal: 0.001}
        joint_3: {trajectory: 6.28, goal: 0.001}
        joint_4: {trajectory: 6.28, goal: 0.03}
        joint_5: {trajectory: 6.28, goal: 0.03}
        joint_6: {trajectory: 6.28, goal: 0.03}
    stop_trajectory_duration: 0.0
    state_publish_rate: 20
    allow_partial_joints_goal: true # to send partial joints, so they are not all updated for the jog joints
    action_monitor_rate: 10
