dynamixels:
    dxl_1:
        # assembly offset position (rad)
        offset_position: -3.1415
        # home position (rad)
        default_home_position: 0.0
        direction: 1
        # assembly direction (1 or -1)
        limit_position_max: 2.09
        limit_position_min: -2.09
        position_P_gain: 1500
        position_I_gain: 4000
        position_D_gain: 50
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 80  # profile acc and vel used by dxl motors
        velocity_profile: 170

    dxl_2:
        offset_position: 2.35619
        default_home_position: 0.0
        direction: -1
        limit_position_max: 1.92
        limit_position_min: -1.92
        position_P_gain: 1000
        position_I_gain: 4000
        position_D_gain: 50
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 70  # profile acc and vel used by dxl motors
        velocity_profile: 140

    dxl_3:
        offset_position: -3.1415
        default_home_position: 0.0
        direction: 1
        limit_position_max: 3.1415
        limit_position_min: -3.1415
        position_P_gain: 1500
        position_I_gain: 4000
        position_D_gain: 50
        velocity_P_gain: 0
        velocity_I_gain: 0
        FF1_gain: 0
        FF2_gain: 0
        acceleration_profile: 105  # profile acc and vel used by dxl motors
        velocity_profile: 210
