publish_io_state_frequency: 10
check_interrupt_flag_security_frequency: 4

button:
  gpio: 4

mcp:
 address: 32
 num_gpios: 16
 i2c_bus: 0
 interrupt_bcm: 26

adc:
  i2c_bus: 0
  address: 54
  v_ref: 4.096

fans:
  - pin: 8
    temperature_on_threshold: 45
    temperature_off_threshold: 40
  - pin: 9
    temperature_on_threshold: 55
    temperature_off_threshold: 50

hotspot:
  led_pin: 4
  button_pin: 5

end_effector_ios:
   digital_input: DI4
   digital_output: DO4

shutdown_manager:
  pins_type: gpio
  digital_output: 8
  digital_input: 25

monitor_12v_pin: 23

digital_inputs:
  - name: DI1
    pin: 0
    reverse: False
  - name: DI2
    pin: 1
    reverse: False
  - name: DI3
    pin: 2
    reverse: False
  - name: DI5
    pin: 3
    reverse: False

digital_outputs:
  - name: DO1
    pin: 12
    reverse: False
  - name: DO2
    pin: 11
    reverse: False
  - name: DO3
    pin: 10
    reverse: False

analog_outputs:
  - name: AO1
    pin: 0
    address: 73
    i2c_bus: 0
    v_ref: 2.5
    resolution: 12
  - name: AO2
    pin: 0
    address: 75
    i2c_bus: 0
    v_ref: 2.5
    resolution: 12

analog_inputs:
  - name: AI1
    pin: 0
    dividing_bridge_factor: 0.781181619
  - name: AI2
    pin: 1
    dividing_bridge_factor: 0.781181619

sound_card:
  i2c_address: 26
  i2c_bus: 1