#
#  Stepper caracteristics for Ned's hardware
#

steppers:
    stepper_1:
        id: 2
        # gear_ratio, max_effort and micro_steps not used for ttl steppers
        motor_ratio: 0.001
        # assembly offset position (rad)
        offset_position: 0.0
        # home position (rad)
        home_position: 0.0
        limit_position_min: -2.96  # joint limit min
        limit_position_max: 2.96  # joint limit max
        # assembly direction (1 or -1)
        direction: 1
        a_max: 4.363
        v_max: 1.571

    stepper_2:
        id: 3
        motor_ratio: 0.001
        offset_position: 0.0
        home_position: 0.5
        limit_position_max: 0.44
        limit_position_min: -1.75
        direction: 1
        a_max: 2.18
        v_max: 1.047
        
    stepper_3:
        id: 4
        motor_ratio: 0.001
        offset_position: 0.0
        home_position: -1.25
        limit_position_min: -1.22
        limit_position_max: 1.57
        direction: 1
        a_max: 4.363
        v_max: 1.571

