# 120 is the maximum stable frequency at which the control loop can run.
ttl_hardware_control_loop_frequency: 120.0
ttl_hardware_read_end_effector_frequency: 13.0
ttl_hardware_read_status_frequency: 0.7
